packages:
  - "apps/*"
  - "packages/*"
  - "projects/*"

overrides:
  "@types/react": "^18.3.18"
  "@types/react-dom": "^18.3.5"

onlyBuiltDependencies:
  - puppeteer
  - "@prisma/client"
  - "@prisma/engines"
  - "@prisma/fetch-engine"
  - "core-js"
  - "esbuild"
  - "prisma"
