/**
 * CanonicalDataModelContract
 *
 * Single authoritative source for the data model used in every generation run.
 *
 * Rules:
 * - DataArchitectureAgent MUST conform to these models.
 * - CoderAgent MUST NOT introduce models not in this list.
 * - PrismaSchemaValidator uses this to verify generated schema.prisma.
 * - All API contracts use these model shapes.
 *
 * Models:
 *   User → Resume (1:N)
 *   User → JobDescription (1:N)
 *   User → MatchAnalysis (1:N)
 *   Resume → MatchAnalysis (1:N)
 *   JobDescription → MatchAnalysis (1:N)
 */
export class CanonicalDataModelContract {
  public static readonly RESUME_MODEL_NAMES = ["User", "Resume", "JobDescription", "AnalysisResult", "KeywordMatch"] as const;
  public static readonly SECURITY_MODEL_NAMES = ["User", "Repository", "Scan", "Vulnerability", "Remediation", "AnalysisResult"] as const;

  /**
   * Returns the canonical Prisma schema string dynamically based on prompt domain.
   */
  public static getPrismaSchema(promptText: string = ""): string {
    const pLower = promptText.toLowerCase();
    const isSecurity = pLower.includes("code") || pLower.includes("vulnerability") || pLower.includes("reviewer") || pLower.includes("security") || pLower.includes("scanner");

    if (isSecurity) {
      return `// ============================================================
// CANONICAL DATA MODEL — Auto-generated by Aegis CanonicalDataModelContract (Code Reviewer Domain)
// ============================================================
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id           String           @id @default(uuid())
  email        String           @unique
  passwordHash String
  createdAt    DateTime         @default(now())
  updatedAt    DateTime         @updatedAt
  repositories Repository[]
  scans        Scan[]
  analyses     AnalysisResult[]
}

model Repository {
  id        String   @id @default(uuid())
  userId    String
  name      String
  url       String
  branch    String   @default("main")
  createdAt DateTime @default(now())
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  scans     Scan[]
}

model Scan {
  id              String          @id @default(uuid())
  userId          String
  repositoryId    String?
  riskScore       Float           @default(0.0)
  status          String          @default("COMPLETED")
  codeSnippet     String?         @db.Text
  vulnerabilities Vulnerability[]
  remediations    Remediation[]
  createdAt       DateTime        @default(now())
  user            User            @relation(fields: [userId], references: [id], onDelete: Cascade)
  repository      Repository?     @relation(fields: [repositoryId], references: [id], onDelete: SetNull)
  analyses        AnalysisResult[]
}

model Vulnerability {
  id          String   @id @default(uuid())
  scanId      String
  title       String
  severity    String
  cve         String?
  filePath    String
  lineNumber  Int      @default(1)
  description String   @db.Text
  scan        Scan     @relation(fields: [scanId], references: [id], onDelete: Cascade)
}

model Remediation {
  id            String   @id @default(uuid())
  scanId        String
  title         String
  suggestedFix  String   @db.Text
  scan          Scan     @relation(fields: [scanId], references: [id], onDelete: Cascade)
}

model AnalysisResult {
  id              String   @id @default(uuid())
  userId          String
  scanId          String?
  matchScore      Float    @default(85.0)
  matchedKeywords String[]
  missingKeywords String[]
  suggestions     String[]
  createdAt       DateTime @default(now())
  user            User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  scan            Scan?    @relation(fields: [scanId], references: [id], onDelete: SetNull)
}
`;
    }

    return `// ============================================================
// CANONICAL DATA MODEL — Auto-generated by Aegis CanonicalDataModelContract (Resume Scanner Domain)
// ============================================================
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id           String           @id @default(uuid())
  email        String           @unique
  passwordHash String
  createdAt    DateTime         @default(now())
  updatedAt    DateTime         @updatedAt
  resumes      Resume[]
  jobDescs     JobDescription[]
  analyses     AnalysisResult[]
}

model Resume {
  id            String           @id @default(uuid())
  userId        String
  filename      String
  extractedText String           @db.Text
  createdAt     DateTime         @default(now())
  user          User             @relation(fields: [userId], references: [id], onDelete: Cascade)
  analyses      AnalysisResult[]
}

model JobDescription {
  id        String           @id @default(uuid())
  userId    String
  title     String
  rawText   String           @db.Text
  createdAt DateTime         @default(now())
  user      User             @relation(fields: [userId], references: [id], onDelete: Cascade)
  analyses  AnalysisResult[]
}

model AnalysisResult {
  id                 String         @id @default(uuid())
  userId             String
  resumeId           String
  jobDescriptionId   String
  matchScore         Float
  matchedKeywords    String[]
  missingKeywords    String[]
  suggestions        String[]
  createdAt          DateTime       @default(now())
  user               User           @relation(fields: [userId], references: [id], onDelete: Cascade)
  resume             Resume         @relation(fields: [resumeId], references: [id], onDelete: Cascade)
  jobDescription     JobDescription @relation(fields: [jobDescriptionId], references: [id], onDelete: Cascade)
  keywordMatches     KeywordMatch[]
}

model KeywordMatch {
  id               String         @id @default(uuid())
  analysisResultId String
  keyword          String
  category         String?
  isMatched        Boolean
  analysisResult   AnalysisResult @relation(fields: [analysisResultId], references: [id], onDelete: Cascade)
}
`;
  }

  /**
   * Returns canonical model names based on prompt.
   */
  public static getModelNames(promptText: string = ""): string[] {
    const pLower = promptText.toLowerCase();
    const isSecurity = pLower.includes("code") || pLower.includes("vulnerability") || pLower.includes("reviewer") || pLower.includes("security") || pLower.includes("scanner");
    return isSecurity ? [...CanonicalDataModelContract.SECURITY_MODEL_NAMES] : [...CanonicalDataModelContract.RESUME_MODEL_NAMES];
  }

  /**
   * Validates that a Prisma schema string contains required canonical model definitions.
   */
  public static validateSchema(schemaContent: string, promptText: string = ""): { valid: boolean; missingModels: string[] } {
    const missingModels: string[] = [];
    const required = CanonicalDataModelContract.getModelNames(promptText);
    for (const model of required) {
      const pattern = new RegExp(`model\\s+${model}\\s*\\{`, "m");
      if (!pattern.test(schemaContent)) {
        missingModels.push(model);
      }
    }
    return { valid: missingModels.length === 0, missingModels };
  }

  /**
   * Returns the canonical API contract for the analysis endpoint.
   * Frontend and backend MUST conform to this shape.
   */
  public static getAnalysisApiContract() {
    return {
      path: "/api/analysis/analyze",
      method: "POST",
      request: {
        resumeText: "string",
        jobDescriptionText: "string",
      },
      response: {
        matchScore: "number",
        matchedKeywords: "string[]",
        missingKeywords: "string[]",
        suggestions: "string[]",
      },
    };
  }

  /**
   * Returns canonical API contract for scan history.
   */
  public static getScanHistoryApiContract() {
    return {
      path: "/api/analysis/history",
      method: "GET",
      response: {
        analyses: "AnalysisResult[]",
      },
    };
  }
}

export class CanonicalPrismaModelRegistry {
  public static readonly MODEL_DELEGATES = ["user", "resume", "jobDescription", "analysisResult", "keywordMatch"] as const;

  public static getRegistry(): Record<string, string> {
    return {
      user: "User",
      resume: "Resume",
      jobDescription: "JobDescription",
      analysisResult: "AnalysisResult",
      keywordMatch: "KeywordMatch",
    };
  }

  public static isValidDelegate(delegateName: string): boolean {
    const validDelegates = new Set(["user", "resume", "jobdescription", "analysisresult", "keywordmatch"]);
    return validDelegates.has(delegateName.toLowerCase());
  }
}

export class PrismaDelegateOperationRegistry {
  public static readonly OPERATIONS = [
    "findUnique",
    "findUniqueOrThrow",
    "findFirst",
    "findFirstOrThrow",
    "findMany",
    "create",
    "createMany",
    "createManyAndReturn",
    "update",
    "updateMany",
    "updateManyAndReturn",
    "upsert",
    "delete",
    "deleteMany",
    "count",
    "aggregate",
    "groupBy",
  ] as const;

  public static isValidOperation(operation: string): boolean {
    return (PrismaDelegateOperationRegistry.OPERATIONS as readonly string[]).includes(operation);
  }
}

export class CanonicalPrismaFieldRegistry {
  public static getFields(modelName: string): Set<string> | null {
    const lower = modelName.toLowerCase();
    switch (lower) {
      case "user":
        return new Set(["id", "email", "passwordHash", "createdAt", "updatedAt", "resumes", "jobDescs", "analyses"]);
      case "resume":
        return new Set(["id", "userId", "filename", "extractedText", "createdAt", "user", "analyses"]);
      case "jobdescription":
        return new Set(["id", "userId", "title", "rawText", "createdAt", "user", "analyses"]);
      case "analysisresult":
        return new Set([
          "id", "userId", "resumeId", "jobDescriptionId", "matchScore",
          "matchedKeywords", "missingKeywords", "suggestions", "createdAt",
          "user", "resume", "jobDescription", "keywordMatches"
        ]);
      case "keywordmatch":
        return new Set(["id", "analysisResultId", "keyword", "category", "isMatched", "analysisResult"]);
      default:
        return null;
    }
  }
}
