import type { ProjectSpecification } from "../architect/specification.js";
import type { GeneratedFile } from "../writer/writer.js";
import { DomainVisualContractGenerator, type DomainVisualDesignContract } from "./domain-visual-contract.js";

export interface DesignTokens {
  brand: string;
  neutral: string;
  radius: string;
  spacing: string;
  font: string;
  style: "minimal" | "bold" | "elegant" | "technical" | "luxury" | "expressive";
}

/**
 * DesignSystemGenerator
 *
 * Generates a contract-driven design system before any UI code is written.
 * Components produced by the CoderAgent and DeterministicFixer import tokens from here.
 * Design language, palette, typography, shapes, and components adapt dynamically
 * based on the DomainVisualDesignContract.
 */
export class DesignSystemGenerator {

  public getVisualContract(spec: ProjectSpecification, promptOverride?: string): DomainVisualDesignContract {
    const p = promptOverride || spec.name || (spec.dataModels || []).join(" ");
    return DomainVisualContractGenerator.deriveContract(p, spec);
  }

  generate(spec: ProjectSpecification, visualContract?: DomainVisualDesignContract): GeneratedFile[] {
    const contract = visualContract || this.getVisualContract(spec);
    const files: GeneratedFile[] = [];

    const brand = contract.colorSystem.primary;
    const neutral = contract.colorSystem.secondary;
    const font = contract.typography.fontFamily;
    const radius = contract.visualPersonality.density === "compact" ? "sm" : contract.visualPersonality.density === "spacious" ? "xl" : "md";

    // ── 1. tokens.ts ─────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/tokens.ts",
      content: `/**
 * Design System Tokens
 * Generated by Aegis Domain-Adaptive Design System Generator.
 * Domain: ${contract.domain} (${contract.productType})
 * Visual Personality: ${contract.visualPersonality.mood}
 */

export const visualContract = ${JSON.stringify(contract, null, 2)} as const;

export const colors = {
  brand: {
    50:  "var(--color-brand-50)",
    100: "var(--color-brand-100)",
    200: "var(--color-brand-200)",
    300: "var(--color-brand-300)",
    400: "var(--color-brand-400)",
    500: "var(--color-brand-500)",
    600: "var(--color-brand-600)",
    700: "var(--color-brand-700)",
    800: "var(--color-brand-800)",
    900: "var(--color-brand-900)",
  },
  neutral: {
    50:  "var(--color-neutral-50)",
    100: "var(--color-neutral-100)",
    200: "var(--color-neutral-200)",
    300: "var(--color-neutral-300)",
    400: "var(--color-neutral-400)",
    500: "var(--color-neutral-500)",
    600: "var(--color-neutral-600)",
    700: "var(--color-neutral-700)",
    800: "var(--color-neutral-800)",
    900: "var(--color-neutral-900)",
    950: "var(--color-neutral-950)",
  },
  semantic: {
    success: "${contract.colorSystem.success}",
    warning: "${contract.colorSystem.warning}",
    error:   "${contract.colorSystem.danger}",
    info:    "var(--color-brand-500)",
  },
} as const;

export const spacing = {
  px: "1px",
  0:  "0",
  1:  "0.25rem",
  2:  "0.5rem",
  3:  "0.75rem",
  4:  "1rem",
  5:  "1.25rem",
  6:  "1.5rem",
  8:  "2rem",
  10: "2.5rem",
  12: "3rem",
  16: "4rem",
} as const;

export const radius = {
  none: "0",
  sm:   "0.25rem",
  md:   "0.375rem",
  DEFAULT: "${radius === "sm" ? "0.25rem" : radius === "xl" ? "0.75rem" : "0.375rem"}",
  lg:   "0.5rem",
  xl:   "0.75rem",
  "2xl":"1rem",
  full: "9999px",
} as const;

export const typography = {
  fontFamily: {
    sans: ["${font}", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Fira Code", "monospace"],
  },
  headingStyle: "${contract.typography.headingStyle}",
  bodyStyle: "${contract.typography.bodyStyle}",
  emphasis: "${contract.typography.emphasis}",
} as const;
`,
    });

    // ── 2. Button.tsx ─────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Button.tsx",
      content: `import React from 'react';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'accent' | string;
export type ButtonSize = 'sm' | 'md' | 'lg' | string;

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: any;
  size?: any;
  loading?: boolean;
  icon?: React.ReactNode;
  children?: React.ReactNode;
  [key: string]: any;
}

const variantClasses: Record<string, string> = {
  primary:   'bg-${brand}-600 text-white hover:bg-${brand}-500 focus-visible:ring-${brand}-500 shadow-md shadow-${brand}-950/30',
  accent:    'bg-gradient-to-r ${contract.colorSystem.accent} text-white hover:brightness-110 shadow-md shadow-black/40',
  secondary: '${contract.colorSystem.surface} text-${neutral}-200 hover:brightness-125 focus-visible:ring-${neutral}-600',
  ghost:     'text-${neutral}-400 hover:text-${neutral}-100 hover:bg-${neutral}-800/40 focus-visible:ring-${neutral}-600',
  danger:    'bg-rose-600 text-white hover:bg-rose-500 focus-visible:ring-rose-500 shadow-sm',
};

const sizeClasses: Record<string, string> = {
  sm: 'px-3 py-1.5 text-xs gap-1.5',
  md: 'px-4 py-2 text-sm gap-2',
  lg: 'px-6 py-3 text-base gap-2.5',
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  icon,
  children,
  disabled,
  className = '',
  ...props
}) => {
  const isDisabled = disabled || loading;
  return (
    <button
      disabled={isDisabled}
      aria-disabled={isDisabled}
      aria-busy={loading}
      className={[
        'inline-flex items-center justify-center font-medium rounded-${radius}',
        'transition-all duration-150 active:scale-[0.98]',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2',
        'disabled:opacity-40 disabled:cursor-not-allowed',
        variantClasses[variant] || variantClasses.primary,
        sizeClasses[size] || sizeClasses.md,
        className,
      ].join(' ')}
      {...props}
    >
      {loading && (
        <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24" aria-hidden="true">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
      )}
      {!loading && icon && <span aria-hidden="true">{icon}</span>}
      {children && <span>{children}</span>}
    </button>
  );
};
export default Button;
`,
    });

    // ── 3. GlassCard.tsx ──────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/GlassCard.tsx",
      content: `import React from 'react';

export const GlassCard: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({ children, className = '', ...props }) => (
  <div className={\`${contract.colorSystem.card} rounded-${radius} p-6 transition-all duration-200 hover:border-${brand}-500/30 \${className}\`} {...props}>
    {children}
  </div>
);
export default GlassCard;
`,
    });

    // ── 4. Skeleton.tsx ───────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Skeleton.tsx",
      content: `import React from 'react';

interface SkeletonProps {
  className?: string;
  lines?: number;
  count?: number;
  height?: string | number;
  width?: string | number;
}

export const Skeleton: React.FC<SkeletonProps> = ({ className = '', lines = 1, count }) => {
  const effectiveLines = count ?? lines;
  if (effectiveLines > 1) {
    return (
      <div className="space-y-2.5" role="status" aria-label="Loading">
        {Array.from({ length: effectiveLines }).map((_, i) => (
          <div
            key={i}
            className={\`h-4 rounded-${radius} bg-${neutral}-800/60 animate-pulse \${i === effectiveLines - 1 ? 'w-3/4' : 'w-full'} \${className}\`}
          />
        ))}
      </div>
    );
  }
  return (
    <div
      role="status"
      aria-label="Loading"
      className={\`rounded-${radius} bg-${neutral}-800/60 animate-pulse \${className}\`}
    />
  );
};
export default Skeleton;
`,
    });

    // ── 5. EmptyState.tsx ─────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/EmptyState.tsx",
      content: `import React from 'react';

interface EmptyStateProps {
  icon?: React.ReactNode;
  title: string;
  description?: string;
  action?: React.ReactNode;
}

export const EmptyState: React.FC<EmptyStateProps> = ({ icon, title, description, action }) => (
  <div className="flex flex-col items-center justify-center py-16 px-4 text-center ${contract.colorSystem.surface} rounded-${radius} border border-dashed">
    {icon && (
      <div className="mb-4 text-${brand}-400/80 p-3 rounded-full bg-${brand}-500/10 border border-${brand}-500/20" aria-hidden="true">
        {icon}
      </div>
    )}
    <h3 className="text-base font-semibold ${contract.colorSystem.textPrimary} mb-1">${contract.typography.headingStyle} {title}</h3>
    {description && (
      <p className="text-sm ${contract.colorSystem.textMuted} max-w-sm mb-6">{description}</p>
    )}
    {action && <div>{action}</div>}
  </div>
);
export default EmptyState;
`,
    });

    // ── 6. Timeline.tsx (Specialized Component) ──────────────────────────────
    files.push({
      path: "src/design-system/components/Timeline.tsx",
      content: `import React from 'react';

export interface TimelineEvent {
  id: string;
  title: string;
  timestamp: string;
  description?: string;
  status?: string;
  icon?: React.ReactNode;
  highlight?: boolean;
}

export interface TimelineProps {
  events: TimelineEvent[];
  title?: string;
  className?: string;
}

export const Timeline: React.FC<TimelineProps> = ({ events, title, className = '' }) => {
  return (
    <div className={\`${contract.colorSystem.card} rounded-${radius} p-6 \${className}\`}>
      {title && <h3 className="text-base font-semibold ${contract.colorSystem.textPrimary} mb-4">{title}</h3>}
      <div className="relative pl-6 border-l border-${neutral}-800 space-y-6">
        {events.map((event) => (
          <div key={event.id} className="relative group">
            <div className={\`absolute -left-[31px] top-1 h-4 w-4 rounded-full border-2 \${event.highlight ? 'bg-${brand}-500 border-${brand}-300 shadow-sm shadow-${brand}-500/50' : 'bg-${neutral}-900 border-${neutral}-700'}\`} />
            <div className="flex items-center justify-between gap-2">
              <span className="text-sm font-medium ${contract.colorSystem.textPrimary}">{event.title}</span>
              <span className="text-xs ${contract.colorSystem.textMuted} font-mono">{event.timestamp}</span>
            </div>
            {event.description && <p className="text-xs ${contract.colorSystem.textMuted} mt-1">{event.description}</p>}
            {event.status && (
              <span className="inline-block mt-2 text-[10px] px-2 py-0.5 rounded-full ${contract.colorSystem.badgeStyle}">
                {event.status}
              </span>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
export default Timeline;
`,
    });

    // ── 7. KanbanBoard.tsx (Specialized Component) ───────────────────────────
    files.push({
      path: "src/design-system/components/KanbanBoard.tsx",
      content: `import React from 'react';

export interface KanbanItem {
  id: string;
  title: string;
  subtitle?: string;
  status: string;
  tags?: string[];
  metrics?: string;
}

export interface KanbanBoardProps {
  columns: { id: string; title: string; count?: number }[];
  items: KanbanItem[];
  onItemClick?: (item: KanbanItem) => void;
  className?: string;
}

export const KanbanBoard: React.FC<KanbanBoardProps> = ({ columns, items, onItemClick, className = '' }) => {
  return (
    <div className={\`grid grid-cols-1 md:grid-cols-\${Math.min(columns.length, 4)} gap-4 \${className}\`}>
      {columns.map(col => {
        const colItems = items.filter(i => i.status.toLowerCase() === col.id.toLowerCase() || i.status.toLowerCase() === col.title.toLowerCase());
        return (
          <div key={col.id} className="${contract.colorSystem.surface} rounded-${radius} p-4 flex flex-col gap-3 min-h-[320px]">
            <div className="flex items-center justify-between pb-2 border-b border-${neutral}-800/80">
              <span className="text-xs font-semibold uppercase tracking-wider ${contract.colorSystem.textPrimary}">{col.title}</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full ${contract.colorSystem.badgeStyle} font-mono">{colItems.length}</span>
            </div>
            <div className="space-y-2.5 overflow-y-auto max-h-[500px]">
              {colItems.map(item => (
                <div
                  key={item.id}
                  onClick={() => onItemClick?.(item)}
                  className="${contract.colorSystem.card} rounded-${radius} p-3 cursor-pointer hover:border-${brand}-500/50 transition-all text-left"
                >
                  <div className="text-sm font-medium ${contract.colorSystem.textPrimary}">{item.title}</div>
                  {item.subtitle && <div className="text-xs ${contract.colorSystem.textMuted} mt-0.5">{item.subtitle}</div>}
                  {item.metrics && <div className="text-[11px] font-mono text-${brand}-400 mt-2">{item.metrics}</div>}
                  {item.tags && item.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1 mt-2">
                      {item.tags.map((t, idx) => (
                        <span key={idx} className="text-[9px] px-1.5 py-0.5 rounded ${contract.colorSystem.badgeStyle}">{t}</span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
              {colItems.length === 0 && (
                <div className="text-center py-8 text-xs ${contract.colorSystem.textMuted} italic">No active items</div>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
};
export default KanbanBoard;
`,
    });

    // ── 8. TelemetryGrid.tsx (Specialized Component) ─────────────────────────
    files.push({
      path: "src/design-system/components/TelemetryGrid.tsx",
      content: `import React from 'react';

export interface TelemetryMetric {
  id: string;
  label: string;
  value: string | number;
  unit?: string;
  status?: 'optimal' | 'warning' | 'critical' | 'idle';
  trend?: string;
}

export interface TelemetryGridProps {
  metrics: TelemetryMetric[];
  title?: string;
  className?: string;
}

export const TelemetryGrid: React.FC<TelemetryGridProps> = ({ metrics, title, className = '' }) => {
  return (
    <div className={\`${contract.colorSystem.card} rounded-${radius} p-6 \${className}\`}>
      {title && (
        <div className="flex items-center justify-between mb-4 pb-2 border-b border-${neutral}-800">
          <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-${brand}-400 flex items-center gap-2">
            <span className="inline-block h-2 w-2 rounded-full bg-${brand}-500 animate-ping" />
            {title}
          </h3>
          <span className="text-[10px] font-mono ${contract.colorSystem.textMuted}">LIVE TELEMETRY STREAM</span>
        </div>
      )}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
        {metrics.map(m => (
          <div key={m.id} className="${contract.colorSystem.surface} rounded-${radius} p-3 border">
            <div className="text-[11px] font-mono ${contract.colorSystem.textMuted} truncate">{m.label}</div>
            <div className="text-lg font-mono font-bold ${contract.colorSystem.textPrimary} mt-1 flex items-baseline gap-1">
              {m.value}
              {m.unit && <span className="text-xs font-normal ${contract.colorSystem.textMuted}">{m.unit}</span>}
            </div>
            {m.trend && <div className="text-[10px] font-mono text-${brand}-400/90 mt-1">{m.trend}</div>}
          </div>
        ))}
      </div>
    </div>
  );
};
export default TelemetryGrid;
`,
    });

    // ── 9. ShowcaseGrid.tsx (Specialized Component) ──────────────────────────
    files.push({
      path: "src/design-system/components/ShowcaseGrid.tsx",
      content: `import React from 'react';

export interface ShowcaseCardItem {
  id: string;
  title: string;
  category: string;
  subtitle?: string;
  status?: string;
  rating?: string | number;
  highlightText?: string;
  imageUrl?: string;
}

export interface ShowcaseGridProps {
  items: ShowcaseCardItem[];
  onSelect?: (item: ShowcaseCardItem) => void;
  className?: string;
}

export const ShowcaseGrid: React.FC<ShowcaseGridProps> = ({ items, onSelect, className = '' }) => {
  return (
    <div className={\`grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 \${className}\`}>
      {items.map(item => (
        <div
          key={item.id}
          onClick={() => onSelect?.(item)}
          className="${contract.colorSystem.card} rounded-${radius} overflow-hidden group cursor-pointer hover:border-${brand}-500/50 transition-all duration-300 flex flex-col"
        >
          <div className="h-44 w-full bg-gradient-to-br ${contract.colorSystem.accent} flex items-center justify-center relative p-4">
            <div className="text-white/90 font-serif text-2xl font-bold tracking-tight text-center drop-shadow-md">
              {item.title}
            </div>
            {item.status && (
              <span className="absolute top-3 right-3 text-[10px] px-2.5 py-1 rounded-full bg-black/60 backdrop-blur-md text-white font-medium border border-white/10">
                {item.status}
              </span>
            )}
          </div>
          <div className="p-5 flex-1 flex flex-col justify-between">
            <div>
              <div className="text-xs font-semibold uppercase tracking-wider text-${brand}-400">{item.category}</div>
              <h4 className="text-base font-bold ${contract.colorSystem.textPrimary} mt-1 group-hover:text-${brand}-300 transition-colors">{item.title}</h4>
              {item.subtitle && <p className="text-xs ${contract.colorSystem.textMuted} mt-2 line-clamp-2">{item.subtitle}</p>}
            </div>
            {item.highlightText && (
              <div className="mt-4 pt-3 border-t border-${neutral}-800/80 flex items-center justify-between text-xs">
                <span className="${contract.colorSystem.textMuted}">Rate / Yield:</span>
                <span className="font-bold text-${brand}-300">{item.highlightText}</span>
              </div>
            )}
          </div>
        </div>
      ))}
    </div>
  );
};
export default ShowcaseGrid;
`,
    });

    // ── 10. index.ts ──────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/index.ts",
      content: `export * from './tokens.js';
export * from './components/Button.js';
export * from './components/Skeleton.js';
export * from './components/EmptyState.js';
export * from './components/GlassCard.js';
export * from './components/Timeline.js';
export * from './components/KanbanBoard.js';
export * from './components/TelemetryGrid.js';
export * from './components/ShowcaseGrid.js';
`,
    });

    return files;
  }

  buildCoderContext(spec: ProjectSpecification, visualContract?: DomainVisualDesignContract): string {
    const contract = visualContract || this.getVisualContract(spec);
    return `
DOMAIN VISUAL DESIGN CONTRACT — MANDATORY USAGE:
Domain: ${contract.domain} (${contract.productType})
Visual Personality: ${contract.visualPersonality.mood} [Formality: ${contract.visualPersonality.formality}, Density: ${contract.visualPersonality.density}]
Layout Archetype: ${contract.layoutFamily}
Navigation Strategy: ${contract.navigation.strategy}

Color Palette Tokens:
  Background: ${contract.colorSystem.background}
  Surface / Cards: ${contract.colorSystem.card}
  Primary Accent: ${contract.colorSystem.primary} (${contract.colorSystem.accent})
  Text Primary: ${contract.colorSystem.textPrimary}
  Text Muted: ${contract.colorSystem.textMuted}
  Badges: ${contract.colorSystem.badgeStyle}
  Active Nav: ${contract.colorSystem.activeNavStyle}

Pre-generated Specialized Components available in src/design-system/:
  import { Button, GlassCard, Skeleton, EmptyState, Timeline, KanbanBoard, TelemetryGrid, ShowcaseGrid } from '../design-system/index.js';

ANTI-PATTERNS (STRICTLY PROHIBITED):
${contract.antiPatterns.map(a => `  ✗ ${a}`).join('\n')}

REQUIRED COMPONENT PATTERNS:
  ✓ Use domain-appropriate components: ${contract.components.join(', ')}
  ✓ Follow layout family ${contract.layoutFamily} (NOT a generic card-grid CRUD template)
  ✓ Navigation must match ${contract.navigation.strategy}
  ✓ Every interactive element has hover + focus-visible states matching ${contract.colorSystem.primary}
  ✓ Empty states use EmptyState with domain call-to-action
`;
  }
}
