import type { ProjectSpecification } from "../architect/specification.js";
import type { GeneratedFile } from "../writer/writer.js";

export interface DesignTokens {
  brand: string;
  neutral: string;
  radius: string;
  spacing: string;
  font: string;
  style: "minimal" | "bold" | "elegant" | "technical";
}

/**
 * DesignSystemGenerator
 *
 * Generates a consistent design-system before any UI code is written.
 * Every component produced by the CoderAgent must import tokens from here
 * rather than using ad-hoc Tailwind classes.
 *
 * Design language is chosen based on project type:
 *   saas/dashboard → Linear-inspired (minimal, tight spacing, neutral palette)
 *   app/tool       → Raycast-inspired (dark, precise, keyboard-first)
 *   website        → Vercel/Stripe-inspired (clean, white, strong typography)
 *   api/cli        → Technical (monospace accents, functional)
 */
export class DesignSystemGenerator {

  private chooseDesignLanguage(spec: ProjectSpecification): DesignTokens {
    const type = spec.type?.toLowerCase() ?? "website";
    const name = spec.name?.toLowerCase() ?? "";

    if (type === "saas" || type === "dashboard") {
      return {
        brand: "indigo",
        neutral: "slate",
        radius: "md",        // 6px — precise, not bubbly
        spacing: "compact",  // 8px grid, tighter
        font: "Inter",
        style: "minimal",
      };
    }
    if (type === "app" || name.includes("tool") || name.includes("scanner")) {
      return {
        brand: "violet",
        neutral: "zinc",
        radius: "lg",        // 8px — modern but not excessive
        spacing: "balanced", // 8px grid
        font: "Inter",
        style: "technical",
      };
    }
    if (type === "api" || type === "cli") {
      return {
        brand: "emerald",
        neutral: "gray",
        radius: "sm",
        spacing: "compact",
        font: "JetBrains Mono",
        style: "technical",
      };
    }
    // Default: website / landing
    return {
      brand: "blue",
      neutral: "slate",
      radius: "md",
      spacing: "balanced",
      font: "Inter",
      style: "elegant",
    };
  }

  generate(spec: ProjectSpecification): GeneratedFile[] {
    const tokens = this.chooseDesignLanguage(spec);
    const files: GeneratedFile[] = [];

    // ── tokens.ts ────────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/tokens.ts",
      content: `/**
 * Design System Tokens
 * Generated by Aegis DesignSystemGenerator.
 * All UI components MUST import from this file — no ad-hoc values.
 */

export const colors = {
  brand: {
    50:  "var(--color-brand-50)",
    100: "var(--color-brand-100)",
    200: "var(--color-brand-200)",
    300: "var(--color-brand-300)",
    400: "var(--color-brand-400)",
    500: "var(--color-brand-500)",
    600: "var(--color-brand-600)",
    700: "var(--color-brand-700)",
    800: "var(--color-brand-800)",
    900: "var(--color-brand-900)",
  },
  neutral: {
    50:  "var(--color-neutral-50)",
    100: "var(--color-neutral-100)",
    200: "var(--color-neutral-200)",
    300: "var(--color-neutral-300)",
    400: "var(--color-neutral-400)",
    500: "var(--color-neutral-500)",
    600: "var(--color-neutral-600)",
    700: "var(--color-neutral-700)",
    800: "var(--color-neutral-800)",
    900: "var(--color-neutral-900)",
    950: "var(--color-neutral-950)",
  },
  semantic: {
    success: "#22c55e",
    warning: "#f59e0b",
    error:   "#ef4444",
    info:    "#3b82f6",
  },
} as const;

export const spacing = {
  px: "1px",
  0:  "0",
  1:  "0.25rem",  // 4px
  2:  "0.5rem",   // 8px  ← base unit
  3:  "0.75rem",  // 12px
  4:  "1rem",     // 16px
  5:  "1.25rem",  // 20px
  6:  "1.5rem",   // 24px
  8:  "2rem",     // 32px
  10: "2.5rem",   // 40px
  12: "3rem",     // 48px
  16: "4rem",     // 64px
  20: "5rem",     // 80px
  24: "6rem",     // 96px
} as const;

export const radius = {
  none: "0",
  sm:   "0.25rem",   // 4px
  md:   "0.375rem",  // 6px
  DEFAULT: "${tokens.radius === "sm" ? "0.25rem" : tokens.radius === "lg" ? "0.5rem" : "0.375rem"}",
  lg:   "0.5rem",    // 8px
  xl:   "0.75rem",   // 12px
  "2xl":"1rem",      // 16px
  full: "9999px",
} as const;

export const typography = {
  fontFamily: {
    sans: ["${tokens.font}", "system-ui", "sans-serif"],
    mono: ["JetBrains Mono", "Fira Code", "monospace"],
  },
  fontSize: {
    xs:   ["0.75rem",  { lineHeight: "1rem" }],
    sm:   ["0.875rem", { lineHeight: "1.25rem" }],
    base: ["1rem",     { lineHeight: "1.5rem" }],
    lg:   ["1.125rem", { lineHeight: "1.75rem" }],
    xl:   ["1.25rem",  { lineHeight: "1.75rem" }],
    "2xl":["1.5rem",   { lineHeight: "2rem" }],
    "3xl":["1.875rem", { lineHeight: "2.25rem" }],
    "4xl":["2.25rem",  { lineHeight: "2.5rem" }],
  },
  fontWeight: {
    normal:    "400",
    medium:    "500",
    semibold:  "600",
    bold:      "700",
    extrabold: "800",
  },
} as const;

export const shadows = {
  sm:  "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  DEFAULT: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  md:  "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  lg:  "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  xl:  "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
} as const;

export const animations = {
  duration: {
    fast:    "100ms",
    normal:  "200ms",
    slow:    "300ms",
    slower:  "500ms",
  },
  easing: {
    default:  "cubic-bezier(0.4, 0, 0.2, 1)",
    in:       "cubic-bezier(0.4, 0, 1, 1)",
    out:      "cubic-bezier(0, 0, 0.2, 1)",
    spring:   "cubic-bezier(0.34, 1.56, 0.64, 1)",
  },
} as const;
`,
    });

    // ── Button.tsx ────────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Button.tsx",
      content: `import React from 'react';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  icon?: React.ReactNode;
  children?: React.ReactNode;
}

const variantClasses: Record<ButtonVariant, string> = {
  primary:   'bg-${tokens.brand}-600 text-white hover:bg-${tokens.brand}-500 focus-visible:ring-${tokens.brand}-500 shadow-sm',
  secondary: 'bg-${tokens.neutral}-800 border border-${tokens.neutral}-700 text-${tokens.neutral}-200 hover:bg-${tokens.neutral}-700 focus-visible:ring-${tokens.neutral}-600',
  ghost:     'text-${tokens.neutral}-400 hover:text-${tokens.neutral}-200 hover:bg-${tokens.neutral}-800/60 focus-visible:ring-${tokens.neutral}-600',
  danger:    'bg-red-600 text-white hover:bg-red-500 focus-visible:ring-red-500 shadow-sm',
};

const sizeClasses: Record<ButtonSize, string> = {
  sm: 'px-3 py-1.5 text-xs gap-1.5',
  md: 'px-4 py-2 text-sm gap-2',
  lg: 'px-6 py-3 text-base gap-2.5',
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  icon,
  children,
  disabled,
  className = '',
  ...props
}) => {
  const isDisabled = disabled || loading;
  return (
    <button
      disabled={isDisabled}
      aria-disabled={isDisabled}
      aria-busy={loading}
      className={[
        'inline-flex items-center justify-center font-medium rounded-md',
        'transition-all duration-150',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-${tokens.neutral}-950',
        'disabled:opacity-40 disabled:cursor-not-allowed',
        variantClasses[variant],
        sizeClasses[size],
        className,
      ].join(' ')}
      {...props}
    >
      {loading && (
        <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24" aria-hidden="true">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
      )}
      {!loading && icon && <span aria-hidden="true">{icon}</span>}
      {children && <span>{children}</span>}
    </button>
  );
};
`,
    });

    // ── Skeleton.tsx ──────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Skeleton.tsx",
      content: `import React from 'react';

interface SkeletonProps {
  className?: string;
  lines?: number;
  count?: number;
  height?: string | number;
  width?: string | number;
}

export const Skeleton: React.FC<SkeletonProps> = ({ className = '', lines = 1, count }) => {
  const effectiveLines = count ?? lines;
  if (effectiveLines > 1) {
    return (
      <div className="space-y-2" role="status" aria-label="Loading">
        {Array.from({ length: effectiveLines }).map((_, i) => (
          <div
            key={i}
            className={\`h-4 rounded-md bg-${tokens.neutral}-800 animate-pulse \${i === effectiveLines - 1 ? 'w-3/4' : 'w-full'} \${className}\`}
          />
        ))}
      </div>
    );
  }
  return (
    <div
      role="status"
      aria-label="Loading"
      className={\`rounded-md bg-${tokens.neutral}-800 animate-pulse \${className}\`}
    />
  );
};
`,
    });

    // ── EmptyState.tsx ────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/EmptyState.tsx",
      content: `import React from 'react';

interface EmptyStateProps {
  icon?: React.ReactNode;
  title: string;
  description?: string;
  action?: React.ReactNode;
}

export const EmptyState: React.FC<EmptyStateProps> = ({ icon, title, description, action }) => (
  <div className="flex flex-col items-center justify-center py-16 px-4 text-center">
    {icon && (
      <div className="mb-4 text-${tokens.neutral}-600" aria-hidden="true">
        {icon}
      </div>
    )}
    <h3 className="text-base font-semibold text-${tokens.neutral}-200 mb-1">{title}</h3>
    {description && (
      <p className="text-sm text-${tokens.neutral}-500 max-w-xs mb-6">{description}</p>
    )}
    {action && <div>{action}</div>}
  </div>
);
`,
    });

    // ── index.ts ──────────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/index.ts",
      content: `export * from './tokens.js';
export * from './components/Button.js';
export * from './components/Skeleton.js';
export * from './components/EmptyState.js';
export * from './components/GlassCard.js';
`,
    });

    return files;
  }

  /**
   * Build the design system context string to inject into the coder system prompt.
   * Tells the CoderAgent what tokens exist and where to import them from.
   */
  buildCoderContext(spec: ProjectSpecification): string {
    const tokens = this.chooseDesignLanguage(spec);
    return `
DESIGN SYSTEM — MANDATORY USAGE:
A design system has been pre-generated at src/design-system/.
You MUST import reusable components from there:
  import { Button, Skeleton, EmptyState } from '../design-system/index.js';

Design Language for this project: ${tokens.style} (inspired by Linear/Vercel/Stripe)
Color palette: ${tokens.brand} brand + ${tokens.neutral} neutral
Spacing: 8px grid (multiples of 2, 4, 6, 8, 10, 12, 16...)
Border radius: ${tokens.radius} (consistent across ALL components)
Font: ${tokens.font}

FORBIDDEN UI PATTERNS:
  ✗ Different border radii on different components (e.g. some rounded-2xl, some rounded-lg)
  ✗ Arbitrary gradient backgrounds not matching the brand palette
  ✗ Buttons larger than 56px height
  ✗ More than 4 different font sizes in a single view
  ✗ Inconsistent spacing that breaks the 8px grid
  ✗ Excessive glassmorphism (max 1 blur panel per page)
  ✗ Missing hover/focus/active states on ANY interactive element
  ✗ Icon-only buttons without aria-label
  ✗ No visible focus indicator (outline-none without focus-visible replacement)

REQUIRED UI PATTERNS:
  ✓ Every interactive element has hover + focus-visible state
  ✓ Destructive actions show a confirmation step before executing
  ✓ Every async operation has a loading skeleton (not just a spinner)
  ✓ Every data-absent state has an EmptyState component with a call-to-action
  ✓ Error states show the actual error message + a recovery action
  ✓ All inputs have labels (visible or aria-label)
  ✓ Responsive at sm (640px), md (768px), lg (1024px) breakpoints
`;
  }
}
