import type { ProjectSpecification } from "../architect/specification.js";
import type { GeneratedFile } from "../writer/writer.js";
import { DomainVisualContractGenerator, type DomainVisualDesignContract } from "./domain-visual-contract.js";
import type { ProductDesignBrief } from "./design-director.js";

export interface DesignTokens {
  brand: string;
  neutral: string;
  radius: string;
  spacing: string;
  font: string;
  style: "minimal" | "bold" | "elegant" | "technical" | "luxury" | "expressive";
}

/**
 * DesignSystemGenerator
 *
 * Generates a contract-driven design system before any UI code is written.
 * Components produced by the CoderAgent and DeterministicFixer import tokens and components from here.
 * Provides a rock-solid, browser-resilient CSS reset, token-driven CSS custom properties,
 * utility/component classes, and Tailwind configuration.
 */
export class DesignSystemGenerator {

  public getVisualContract(spec: ProjectSpecification, promptOverride?: string): DomainVisualDesignContract {
    const p = promptOverride || spec.name || (spec.dataModels || []).join(" ");
    return DomainVisualContractGenerator.deriveContract(p, spec);
  }

  generate(spec: ProjectSpecification, visualContractOrBrief?: DomainVisualDesignContract | ProductDesignBrief): GeneratedFile[] {
    // If a ProductDesignBrief is passed, derive a compatible DomainVisualDesignContract from it
    let contract: DomainVisualDesignContract;
    if (visualContractOrBrief && "artDirectionName" in visualContractOrBrief) {
      // ProductDesignBrief — derive the base contract from the prompt/spec, then
      // overlay the brief's locked tokens. We intentionally do NOT pass the brief
      // as the third arg because deriveContract expects ArchitectureContractV1.
      const brief = visualContractOrBrief as ProductDesignBrief;
      const baseContract = DomainVisualContractGenerator.deriveContract(
        (spec as any).userPrompt || spec.name || "",
        spec,
        // No third arg — brief tokens are overlaid below
      );
      // Overlay brief's palette choices onto the base contract
      contract = {
        ...baseContract,
        artDirection: (brief as any).artDirection ?? baseContract.artDirection,
        colorSystem: {
          ...baseContract.colorSystem,
          primary: (brief as any).primaryColor ?? baseContract.colorSystem.primary,
          mode: (brief as any).colorMode ?? baseContract.colorSystem.mode,
        },
        visualPersonality: {
          ...baseContract.visualPersonality,
          density: (brief as any).density ?? baseContract.visualPersonality.density,
          mood: (brief as any).mood ?? baseContract.visualPersonality.mood,
        },
      } as DomainVisualDesignContract;
    } else {
      contract = (visualContractOrBrief as DomainVisualDesignContract | undefined) || this.getVisualContract(spec);
    }
    const resolved = DomainVisualContractGenerator.resolveCssTokens(contract);
    const files: GeneratedFile[] = [];

    const brand = contract.colorSystem.primary;
    const neutral = contract.colorSystem.secondary;
    const font = contract.typography.fontFamily;
    const radius = contract.visualPersonality.density === "compact" ? "sm" : contract.visualPersonality.density === "spacious" ? "xl" : "md";

    // ── 1. tokens.ts ─────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/tokens.ts",
      content: `/**
 * Design System Tokens
 * Generated by Aegis Domain-Adaptive Design System Generator.
 * Domain: ${contract.domain} (${contract.productType})
 * Visual Personality: ${contract.visualPersonality.mood}
 */

export const visualContract = ${JSON.stringify(contract, null, 2)} as const;
export const resolvedTokens = ${JSON.stringify(resolved, null, 2)} as const;

export const colors = {
  background: "${resolved.backgroundColor}",
  surface: "${resolved.surfaceColor}",
  surfaceElevated: "${resolved.surfaceElevatedColor}",
  primary: "${resolved.primaryColor}",
  primaryHover: "${resolved.primaryHoverColor}",
  primarySubtle: "${resolved.primarySubtleColor}",
  secondary: "${resolved.secondaryColor}",
  border: "${resolved.borderColor}",
  borderSubtle: "${resolved.borderSubtleColor}",
  textPrimary: "${resolved.textPrimaryColor}",
  textSecondary: "${resolved.textSecondaryColor}",
  textMuted: "${resolved.textMutedColor}",
  semantic: {
    success: "${resolved.successColor}",
    warning: "${resolved.warningColor}",
    error:   "${resolved.dangerColor}",
    info:    "${resolved.primaryColor}",
  },
} as const;

export const spacing = {
  px: "1px",
  0:  "0",
  1:  "0.25rem",
  2:  "0.5rem",
  3:  "0.75rem",
  4:  "1rem",
  5:  "1.25rem",
  6:  "1.5rem",
  8:  "2rem",
  10: "2.5rem",
  12: "3rem",
  16: "4rem",
} as const;

export const radiusTokens = {
  sm:   "${resolved.radiusSm}",
  md:   "${resolved.radiusMd}",
  lg:   "${resolved.radiusLg}",
  xl:   "${resolved.radiusXl}",
  full: "${resolved.radiusFull}",
} as const;

export const typography = {
  fontFamily: {
    display: ["${resolved.fontDisplay}", "system-ui", "sans-serif"],
    body: ["${resolved.fontBody}", "system-ui", "sans-serif"],
  },
  headingStyle: "${contract.typography.headingStyle}",
  bodyStyle: "${contract.typography.bodyStyle}",
  emphasis: "${contract.typography.emphasis}",
} as const;
`,
    });

    // ── 2. index.css (Complete CSS Reset + Tokens + Resilient Component Styling) ──
    files.push({
      path: "src/index.css",
      content: `@tailwind base;
@tailwind components;
@tailwind utilities;

/* ═══════════════════════════════════════════════════════════════════════════
 * 1. DOMAIN-AGNOSTIC CSS RESET
 * ═══════════════════════════════════════════════════════════════════════════ */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html,
body,
#root {
  min-height: 100%;
  width: 100%;
}

html {
  -webkit-text-size-adjust: 100%;
  tab-size: 4;
  font-feature-settings: normal;
}

body {
  margin: 0;
  min-height: 100vh;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-family: var(--font-body);
  background-color: var(--color-background);
  color: var(--color-text-primary);
  background-attachment: fixed;
}

#root {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

/* Hyperlinks Reset & Styling */
a {
  color: inherit;
  text-decoration: none;
  transition: color 0.15s ease, opacity 0.15s ease;
}

a:hover {
  opacity: 0.85;
}

/* Button Reset & Normalization */
button {
  font-family: inherit;
  font-size: 100%;
  line-height: 1.15;
  margin: 0;
  cursor: pointer;
  border: none;
  background: transparent;
  color: inherit;
}

/* Form Controls Reset */
input, optgroup, select, textarea {
  font-family: inherit;
  font-size: 100%;
  line-height: 1.15;
  margin: 0;
  color: inherit;
}

/* Media Display */
img, svg, video, canvas, audio, iframe, embed, object {
  display: block;
  max-width: 100%;
}

/* Heading Structure */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-display);
  color: var(--color-text-primary);
  font-weight: 700;
  line-height: 1.25;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * 2. TOKEN-DRIVEN DESIGN SYSTEM VARIABLES (:root)
 * ═══════════════════════════════════════════════════════════════════════════ */
:root {
  --color-background: ${resolved.backgroundColor};
  --color-surface: ${resolved.surfaceColor};
  --color-surface-elevated: ${resolved.surfaceElevatedColor};
  --color-primary: ${resolved.primaryColor};
  --color-primary-hover: ${resolved.primaryHoverColor};
  --color-primary-subtle: ${resolved.primarySubtleColor};
  --color-secondary: ${resolved.secondaryColor};
  --color-accent: ${resolved.primaryColor};
  --color-text-primary: ${resolved.textPrimaryColor};
  --color-text-secondary: ${resolved.textSecondaryColor};
  --color-text-muted: ${resolved.textMutedColor};
  --color-border: ${resolved.borderColor};
  --color-border-subtle: ${resolved.borderSubtleColor};
  --color-success: ${resolved.successColor};
  --color-warning: ${resolved.warningColor};
  --color-danger: ${resolved.dangerColor};

  --radius-sm: ${resolved.radiusSm};
  --radius-md: ${resolved.radiusMd};
  --radius-lg: ${resolved.radiusLg};
  --radius-xl: ${resolved.radiusXl};
  --radius-full: ${resolved.radiusFull};

  --shadow-sm: ${resolved.shadowSm};
  --shadow-md: ${resolved.shadowMd};
  --shadow-lg: ${resolved.shadowLg};

  --surface-blur: ${contract.artDirection?.surfaceTreatment.type === "translucent_glass" ? (contract.artDirection.surfaceTreatment.backdropBlur || "16px") : "0px"};
  --card-shadow: ${contract.artDirection?.surfaceTreatment.cardShadow || resolved.shadowMd};
  --card-border: ${contract.artDirection?.surfaceTreatment.cardBorder || "1px solid var(--color-border)"};
  --nav-group-radius: ${contract.navigation.strategy === "TOPBAR_PILL" ? "var(--radius-full)" : "var(--radius-md)"};

  --space-1: 0.25rem;
  --space-2: 0.5rem;
  --space-3: 0.75rem;
  --space-4: 1rem;
  --space-6: 1.5rem;
  --space-8: 2rem;
  --space-12: 3rem;

  --section-gap: ${contract.visualPersonality.density === "spacious" ? "5rem" : "3.5rem"};
  --hero-padding: ${contract.visualPersonality.density === "spacious" ? "4.5rem 0 3.5rem 0" : "2.5rem 0 1.5rem 0"};
  --font-display-size: clamp(2.25rem, 5vw, 3.75rem);
  --font-lead-size: 1.125rem;

  --font-display: ${resolved.fontDisplay};
  --font-body: ${resolved.fontBody};
}

/* ═══════════════════════════════════════════════════════════════════════════
 * 3. RESILIENT DOMAIN-ADAPTIVE COMPONENT & LAYOUT CLASSES
 * ═══════════════════════════════════════════════════════════════════════════ */

/* Modern Typography Scale */
.display-title {
  font-family: var(--font-display);
  font-size: var(--font-display-size);
  font-weight: 800;
  line-height: 1.08;
  letter-spacing: -0.035em;
  color: var(--color-text-primary);
}

.section-heading {
  font-family: var(--font-display);
  font-size: clamp(1.5rem, 3vw, 2.25rem);
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.025em;
  color: var(--color-text-primary);
}

.body-lead {
  font-size: var(--font-lead-size);
  line-height: 1.65;
  color: var(--color-text-secondary);
  max-width: 46rem;
}

/* Surface Treatment Variations */
.surface-borderless {
  background: transparent;
  border: none;
  box-shadow: none;
}

.surface-soft {
  background: var(--color-surface);
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-sm);
}

.surface-floating {
  background: var(--color-surface);
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-lg);
  transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);
}

.surface-floating:hover {
  transform: translateY(-3px);
  box-shadow: 0 14px 28px -6px rgba(0, 0, 0, 0.18);
}

.section-narrative {
  padding: var(--section-gap) 0;
}

.divide-subtle > * + * {
  border-color: var(--color-border-subtle);
}

.border-subtle {
  border-color: var(--color-border-subtle);
}

.surface-flat-ruled {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  box-shadow: none;
  backdrop-filter: none;
  -webkit-backdrop-filter: none;
}

.surface-solid-depth {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  box-shadow: var(--shadow-md);
  backdrop-filter: none;
  -webkit-backdrop-filter: none;
}

.surface-translucent-glass {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  box-shadow: var(--shadow-lg);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
}

/* App Shell & Header */
.app-shell {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: var(--color-background);
  color: var(--color-text-primary);
}

.app-header {
  border-bottom: 1px solid var(--color-border);
  background-color: var(--color-surface);
  backdrop-filter: blur(var(--surface-blur));
  -webkit-backdrop-filter: blur(var(--surface-blur));
  position: sticky;
  top: 0;
  z-index: 40;
  padding: 0.875rem 1.5rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.app-nav {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.nav-pill-group {
  padding: 0.25rem;
  border-radius: var(--nav-group-radius);
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.nav-item, .nav-link {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  border-radius: var(--radius-md);
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--color-text-secondary);
  transition: all 0.15s ease;
  text-decoration: none;
  cursor: pointer;
}

.nav-item:hover, .nav-link:hover {
  color: var(--color-text-primary);
  background: rgba(255, 255, 255, 0.08);
}

.nav-item.active, .nav-link.active {
  color: #ffffff;
  background: var(--color-primary);
  font-weight: 600;
  box-shadow: 0 2px 10px var(--color-primary-subtle);
}

.nav-dropdown {
  position: relative;
  display: inline-block;
}

.nav-dropdown-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.5rem 0.875rem;
  border-radius: var(--radius-md);
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--color-text-secondary);
  transition: all 0.15s ease;
  cursor: pointer;
  border: none;
  background: transparent;
}

.nav-dropdown-btn:hover {
  color: var(--color-text-primary);
  background: rgba(255, 255, 255, 0.08);
}

.nav-dropdown-menu {
  position: absolute;
  top: calc(100% + 0.5rem);
  right: 0;
  min-width: 13rem;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-lg);
  padding: 0.375rem;
  z-index: 50;
  display: flex;
  flex-direction: column;
  gap: 0.125rem;
}

.nav-dropdown-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  font-size: 0.8125rem;
  border-radius: var(--radius-md);
  color: var(--color-text-secondary);
  transition: all 0.15s ease;
  text-decoration: none;
}

.nav-dropdown-item:hover {
  background: rgba(255, 255, 255, 0.08);
  color: var(--color-text-primary);
}

.main-container {
  flex: 1;
  max-width: 1320px;
  width: 100%;
  margin: 0 auto;
  padding: 2rem 2rem;
}

/* Buttons */
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  font-weight: 600;
  font-size: 0.875rem;
  padding: 0.5rem 1.125rem;
  border-radius: var(--radius-md);
  transition: all 0.15s ease;
  cursor: pointer;
  text-decoration: none;
  border: 1px solid transparent;
  line-height: 1.25;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
  transform: none !important;
}

.btn-primary {
  background: var(--color-primary);
  color: #ffffff;
  border-color: var(--color-primary);
  box-shadow: 0 2px 8px var(--color-primary-subtle);
}

.btn-primary:hover:not(:disabled) {
  opacity: 0.92;
  transform: translateY(-1px);
  box-shadow: 0 4px 14px var(--color-primary-subtle);
}

.btn-secondary {
  background: var(--color-surface);
  color: var(--color-text-primary);
  border-color: var(--color-border);
}

.btn-secondary:hover:not(:disabled) {
  background: var(--color-surface-elevated);
  border-color: var(--color-text-secondary);
}

.btn-accent {
  background: linear-gradient(135deg, var(--color-primary), var(--color-warning));
  color: #ffffff;
  box-shadow: var(--shadow-md);
}

.btn-ghost {
  background: transparent;
  color: var(--color-text-secondary);
}

.btn-ghost:hover:not(:disabled) {
  color: var(--color-text-primary);
  background: rgba(255, 255, 255, 0.08);
}

.btn-danger {
  background: var(--color-danger);
  color: #ffffff;
}

.btn-danger:hover:not(:disabled) {
  opacity: 0.9;
}

/* Cards & Surfaces */
.card, .glass-card {
  background: var(--color-surface);
  border: var(--card-border);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  box-shadow: var(--card-shadow);
  backdrop-filter: blur(var(--surface-blur));
  -webkit-backdrop-filter: blur(var(--surface-blur));
  transition: border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease;
}

.card-hover:hover {
  border-color: var(--color-primary);
  transform: translateY(-2px);
  box-shadow: var(--shadow-lg);
}

/* Badges */
.badge {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.25rem 0.625rem;
  border-radius: var(--radius-full);
  font-size: 0.75rem;
  font-weight: 600;
  background: var(--color-primary-subtle);
  color: var(--color-primary);
  border: 1px solid var(--color-border);
}

.badge-live {
  background: rgba(16, 185, 129, 0.15);
  color: #34d399;
  border-color: rgba(16, 185, 129, 0.3);
}

.live-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background-color: var(--color-primary);
  display: inline-block;
}

/* Form Controls */
.form-input, .form-select {
  width: 100%;
  padding: 0.625rem 0.875rem;
  border-radius: var(--radius-md);
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  color: var(--color-text-primary);
  font-size: 0.875rem;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}

.form-input:focus, .form-select:focus {
  outline: none;
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px var(--color-primary-subtle);
}

/* Tables */
.data-table {
  width: 100%;
  border-collapse: separate;
  border-spacing: 0;
  font-size: 0.875rem;
}

.data-table th {
  background: var(--color-surface-elevated);
  color: var(--color-text-secondary);
  font-weight: 600;
  text-align: left;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--color-border);
}

.data-table td {
  padding: 0.875rem 1rem;
  border-bottom: 1px solid var(--color-border-subtle);
  color: var(--color-text-primary);
}

.data-table tr:hover td {
  background: rgba(255, 255, 255, 0.04);
}

/* Telemetry & Metrics */
.metric-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: 1.25rem;
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
}

.metric-value {
  font-size: 1.75rem;
  font-weight: 700;
  color: var(--color-text-primary);
  font-family: var(--font-display);
}

.telemetry-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 1rem;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 4rem 1.5rem;
  text-align: center;
  background: var(--color-surface);
  border: 1px dashed var(--color-border);
  border-radius: var(--radius-lg);
}

.skeleton-box {
  background: var(--color-surface-elevated);
  border-radius: var(--radius-md);
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}
`,
    });

    // ── 3. tailwind.config.js & postcss.config.js ─────────────────────────────
    files.push({
      path: "tailwind.config.js",
      content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-elevated": "var(--color-surface-elevated)",
        primary: "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-subtle": "var(--color-primary-subtle)",
        secondary: "var(--color-secondary)",
        border: "var(--color-border)",
        textPrimary: "var(--color-text-primary)",
        textSecondary: "var(--color-text-secondary)",
        textMuted: "var(--color-text-muted)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      fontFamily: {
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
`,
    });

    files.push({
      path: "postcss.config.js",
      content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
    });

    // ── 4. Button.tsx ─────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Button.tsx",
      content: `import React from 'react';

export type ButtonVariant = 'primary' | 'secondary' | 'accent' | 'ghost' | 'danger';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  icon?: React.ReactNode;
  children?: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  icon,
  children,
  disabled,
  className = '',
  ...props
}) => {
  const isDisabled = disabled || loading;
  const sizeClass = size === 'sm' ? 'px-3 py-1.5 text-xs' : size === 'lg' ? 'px-6 py-3 text-base' : 'px-4 py-2 text-sm';
  const variantClass = \`btn-\${variant}\`;

  return (
    <button
      disabled={isDisabled}
      aria-disabled={isDisabled}
      aria-busy={loading}
      className={\`btn \${variantClass} \${sizeClass} \${className}\`}
      {...props}
    >
      {loading && (
        <svg className="animate-spin h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" aria-hidden="true">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
      )}
      {!loading && icon && <span className="inline-flex mr-1.5" aria-hidden="true">{icon}</span>}
      {children && <span>{children}</span>}
    </button>
  );
};
export default Button;
`,
    });

    // ── 5. GlassCard.tsx ──────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/GlassCard.tsx",
      content: `import React from 'react';

export interface GlassCardProps extends React.HTMLAttributes<HTMLDivElement> {
  hoverable?: boolean;
}

export const GlassCard: React.FC<GlassCardProps> = ({ children, hoverable = false, className = '', ...props }) => (
  <div className={\`glass-card \${hoverable ? 'card-hover' : ''} \${className}\`} {...props}>
    {children}
  </div>
);
export default GlassCard;
`,
    });

    // ── 6. Badge.tsx ──────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Badge.tsx",
      content: `import React from 'react';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'primary' | 'live' | 'warning' | 'danger';
  dot?: boolean;
}

export const Badge: React.FC<BadgeProps> = ({ children, variant = 'primary', dot = false, className = '', ...props }) => {
  const variantClass = variant === 'live' ? 'badge-live' : 'badge';
  return (
    <span className={\`\${variantClass} \${className}\`} {...props}>
      {dot && <span className="live-dot mr-1" />}
      {children}
    </span>
  );
};
export default Badge;
`,
    });

    // ── 7. Input.tsx & Select.tsx ─────────────────────────────────────────────
    files.push({
      path: "src/design-system/components/Input.tsx",
      content: `import React from 'react';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
}

export const Input: React.FC<InputProps> = ({ label, error, className = '', ...props }) => (
  <div className="w-full flex flex-col gap-1.5">
    {label && <label className="text-xs font-semibold text-[var(--color-text-secondary)]">{label}</label>}
    <input className={\`form-input \${className}\`} {...props} />
    {error && <span className="text-xs text-[var(--color-danger)]">{error}</span>}
  </div>
);
export default Input;
`,
    });

    files.push({
      path: "src/design-system/components/Select.tsx",
      content: `import React from 'react';

export interface SelectProps extends React.SelectHTMLAttributes<HTMLSelectElement> {
  label?: string;
  options: Array<{ value: string; label: string }>;
  error?: string;
}

export const Select: React.FC<SelectProps> = ({ label, options, error, className = '', ...props }) => (
  <div className="w-full flex flex-col gap-1.5">
    {label && <label className="text-xs font-semibold text-[var(--color-text-secondary)]">{label}</label>}
    <select className={\`form-select \${className}\`} {...props}>
      {options.map(opt => (
        <option key={opt.value} value={opt.value} className="bg-[var(--color-surface)] text-[var(--color-text-primary)]">
          {opt.label}
        </option>
      ))}
    </select>
    {error && <span className="text-xs text-[var(--color-danger)]">{error}</span>}
  </div>
);
export default Select;
`,
    });

    // ── 8. MetricCard.tsx & PageHeader.tsx ────────────────────────────────────
    files.push({
      path: "src/design-system/components/MetricCard.tsx",
      content: `import React from 'react';

export interface MetricCardProps {
  label: string;
  value: string | number;
  trend?: string;
  icon?: React.ReactNode;
  className?: string;
}

export const MetricCard: React.FC<MetricCardProps> = ({ label, value, trend, icon, className = '' }) => (
  <div className={\`metric-card \${className}\`}>
    <div className="flex items-center justify-between text-xs font-medium text-[var(--color-text-muted)]">
      <span>{label}</span>
      {icon && <span className="text-[var(--color-primary)]">{icon}</span>}
    </div>
    <div className="metric-value mt-1">{value}</div>
    {trend && (
      <div className="text-xs font-medium text-[var(--color-primary)] mt-0.5">
        {trend}
      </div>
    )}
  </div>
);
export default MetricCard;
`,
    });

    files.push({
      path: "src/design-system/components/PageHeader.tsx",
      content: `import React from 'react';

export interface PageHeaderProps {
  title: string;
  description?: string;
  actions?: React.ReactNode;
  badge?: React.ReactNode;
  className?: string;
}

export const PageHeader: React.FC<PageHeaderProps> = ({ title, description, actions, badge, className = '' }) => (
  <div className={\`flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-[var(--color-border)] mb-6 \${className}\`}>
    <div>
      <div className="flex items-center gap-3">
        <h1 className="text-2xl font-bold tracking-tight text-[var(--color-text-primary)]">{title}</h1>
        {badge}
      </div>
      {description && <p className="text-sm text-[var(--color-text-muted)] mt-1">{description}</p>}
    </div>
    {actions && <div className="flex items-center gap-3">{actions}</div>}
  </div>
);
export default PageHeader;
`,
    });

    // ── 9. Skeleton.tsx & EmptyState.tsx ──────────────────────────────────────
    files.push({
      path: "src/design-system/components/Skeleton.tsx",
      content: `import React from 'react';

export const Skeleton: React.FC<{ className?: string; lines?: number }> = ({ className = '', lines = 1 }) => (
  <div className="space-y-2.5 w-full">
    {Array.from({ length: lines }).map((_, i) => (
      <div key={i} className={\`skeleton-box h-4 \${i === lines - 1 && lines > 1 ? 'w-3/4' : 'w-full'} \${className}\`} />
    ))}
  </div>
);
export default Skeleton;
`,
    });

    files.push({
      path: "src/design-system/components/EmptyState.tsx",
      content: `import React from 'react';

export interface EmptyStateProps {
  icon?: React.ReactNode;
  title: string;
  description?: string;
  action?: React.ReactNode;
}

export const EmptyState: React.FC<EmptyStateProps> = ({ icon, title, description, action }) => (
  <div className="empty-state">
    {icon && <div className="mb-4 text-[var(--color-primary)] text-3xl">{icon}</div>}
    <h3 className="text-base font-semibold text-[var(--color-text-primary)] mb-1">{title}</h3>
    {description && <p className="text-sm text-[var(--color-text-muted)] max-w-sm mb-6">{description}</p>}
    {action && <div>{action}</div>}
  </div>
);
export default EmptyState;
`,
    });

    // ── 10. Timeline.tsx & KanbanBoard.tsx ─────────────────────────────────────
    files.push({
      path: "src/design-system/components/Timeline.tsx",
      content: `import React from 'react';

export interface TimelineEvent {
  id: string;
  title: string;
  timestamp: string;
  description?: string;
  status?: string;
}

export interface TimelineProps {
  events: TimelineEvent[];
  title?: string;
  className?: string;
}

export const Timeline: React.FC<TimelineProps> = ({ events, title, className = '' }) => (
  <div className={\`card \${className}\`}>
    {title && <h3 className="text-base font-semibold text-[var(--color-text-primary)] mb-4">{title}</h3>}
    <div className="relative pl-6 border-l-2 border-[var(--color-border)] space-y-6">
      {events.map((event) => (
        <div key={event.id} className="relative">
          <div className="absolute -left-[31px] top-1.5 h-3.5 w-3.5 rounded-full bg-[var(--color-primary)] border-2 border-[var(--color-surface)]" />
          <div className="flex items-center justify-between gap-2">
            <span className="text-sm font-semibold text-[var(--color-text-primary)]">{event.title}</span>
            <span className="text-xs font-mono text-[var(--color-text-muted)]">{event.timestamp}</span>
          </div>
          {event.description && <p className="text-xs text-[var(--color-text-muted)] mt-1">{event.description}</p>}
          {event.status && <span className="inline-block mt-2 badge">{event.status}</span>}
        </div>
      ))}
    </div>
  </div>
);
export default Timeline;
`,
    });

    const isKanbanExplicitlyRequested = (
      (spec.features || []).some((f: any) => {
        const name = (typeof f === "string" ? f : (f?.name || f?.title || "")).toLowerCase();
        return (
          name.includes("kanban") ||
          name.includes("task board") ||
          name.includes("scrum board") ||
          name.includes("workflow board") ||
          name.includes("task management") ||
          name.includes("project management") ||
          (/\bboard\b/.test(name) && !name.includes("dashboard") && !name.includes("leaderboard") && !name.includes("order book"))
        );
      }) ||
      ((spec as any).userPrompt && /\b(kanban|task board|scrum board|sprint board|issue board|task management)\b/i.test((spec as any).userPrompt)) ||
      ((spec as any).description && /\b(kanban|task board|scrum board|sprint board|issue board|task management)\b/i.test((spec as any).description))
    );
    const isKanbanForbidden = ((spec as any).forbiddenPatterns || []).includes("KanbanBoard");
    const needsKanban = !isKanbanForbidden && isKanbanExplicitlyRequested;

    if (needsKanban) {
      files.push({
        path: "src/design-system/components/KanbanBoard.tsx",
        content: `import React from 'react';

export interface KanbanItem {
  id: string;
  title: string;
  subtitle?: string;
  status: string;
  tags?: string[];
}

export interface KanbanBoardProps {
  columns: { id: string; title: string }[];
  items: KanbanItem[];
  onItemClick?: (item: KanbanItem) => void;
  className?: string;
}

export const KanbanBoard: React.FC<KanbanBoardProps> = ({ columns, items, onItemClick, className = '' }) => (
  <div className={\`grid grid-cols-1 md:grid-cols-\${Math.min(columns.length, 4)} gap-4 \${className}\`}>
    {columns.map(col => {
      const colItems = items.filter(i => i.status.toLowerCase() === col.id.toLowerCase() || i.status.toLowerCase() === col.title.toLowerCase());
      return (
        <div key={col.id} className="card flex flex-col gap-3 min-h-[300px]">
          <div className="flex items-center justify-between pb-2 border-b border-[var(--color-border)]">
            <span className="text-xs font-bold uppercase tracking-wider text-[var(--color-text-primary)]">{col.title}</span>
            <span className="badge">{colItems.length}</span>
          </div>
          <div className="space-y-2.5 overflow-y-auto max-h-[480px]">
            {colItems.map(item => (
              <div
                key={item.id}
                onClick={() => onItemClick?.(item)}
                className="card card-hover p-3 cursor-pointer text-left"
              >
                <div className="text-sm font-semibold text-[var(--color-text-primary)]">{item.title}</div>
                {item.subtitle && <div className="text-xs text-[var(--color-text-muted)] mt-0.5">{item.subtitle}</div>}
              </div>
            ))}
          </div>
        </div>
      );
    })}
  </div>
);
export default KanbanBoard;
`,
      });
    }

    // ── 11. TelemetryGrid.tsx & ShowcaseGrid.tsx ──────────────────────────────
    files.push({
      path: "src/design-system/components/TelemetryGrid.tsx",
      content: `import React from 'react';

export interface TelemetryMetric {
  id: string;
  label: string;
  value: string | number;
  unit?: string;
  trend?: string;
}

export interface TelemetryGridProps {
  metrics: TelemetryMetric[];
  title?: string;
  className?: string;
}

export const TelemetryGrid: React.FC<TelemetryGridProps> = ({ metrics, title, className = '' }) => (
  <div className={\`card \${className}\`}>
    {title && (
      <div className="flex items-center justify-between mb-4 pb-2 border-b border-[var(--color-border)]">
        <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-[var(--color-primary)] flex items-center gap-2">
          <span className="live-dot" />
          {title}
        </h3>
        <span className="badge badge-live">LIVE TELEMETRY</span>
      </div>
    )}
    <div className="telemetry-grid">
      {metrics.map(m => (
        <div key={m.id} className="card p-3 border border-[var(--color-border)]">
          <div className="text-xs font-mono text-[var(--color-text-muted)] truncate">{m.label}</div>
          <div className="text-lg font-mono font-bold text-[var(--color-text-primary)] mt-1">
            {m.value} {m.unit && <span className="text-xs font-normal text-[var(--color-text-muted)]">{m.unit}</span>}
          </div>
          {m.trend && <div className="text-xs font-mono text-[var(--color-primary)] mt-1">{m.trend}</div>}
        </div>
      ))}
    </div>
  </div>
);
export default TelemetryGrid;
`,
    });

    files.push({
      path: "src/design-system/components/ShowcaseGrid.tsx",
      content: `import React from 'react';

export interface ShowcaseCardItem {
  id: string;
  title: string;
  category: string;
  subtitle?: string;
  status?: string;
  highlightText?: string;
}

export interface ShowcaseGridProps {
  items: ShowcaseCardItem[];
  onSelect?: (item: ShowcaseCardItem) => void;
  className?: string;
}

export const ShowcaseGrid: React.FC<ShowcaseGridProps> = ({ items, onSelect, className = '' }) => (
  <div className={\`grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 \${className}\`}>
    {items.map(item => (
      <div
        key={item.id}
        onClick={() => onSelect?.(item)}
        className="card card-hover overflow-hidden cursor-pointer flex flex-col justify-between"
      >
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-bold uppercase text-[var(--color-primary)]">{item.category}</span>
            {item.status && <span className="badge">{item.status}</span>}
          </div>
          <h4 className="text-base font-bold text-[var(--color-text-primary)]">{item.title}</h4>
          {item.subtitle && <p className="text-xs text-[var(--color-text-muted)] mt-1 line-clamp-2">{item.subtitle}</p>}
        </div>
        {item.highlightText && (
          <div className="mt-4 pt-3 border-t border-[var(--color-border)] flex items-center justify-between text-xs">
            <span className="text-[var(--color-text-muted)]">Metric:</span>
            <span className="font-bold text-[var(--color-primary)]">{item.highlightText}</span>
          </div>
        )}
      </div>
    ))}
  </div>
);
export default ShowcaseGrid;
`,
    });

    // ── 12. index.ts ──────────────────────────────────────────────────────────
    files.push({
      path: "src/design-system/index.ts",
      content: `export * from './tokens';
export * from './components/Button';
export * from './components/GlassCard';
export * from './components/Badge';
export * from './components/Input';
export * from './components/Select';
export * from './components/MetricCard';
export * from './components/PageHeader';
export * from './components/Skeleton';
export * from './components/EmptyState';
export * from './components/Timeline';
${needsKanban ? "export * from './components/KanbanBoard';\n" : ""}export * from './components/TelemetryGrid';
export * from './components/ShowcaseGrid';
`,
    });

    return files;
  }

  buildCoderContext(spec: ProjectSpecification, visualContract?: DomainVisualDesignContract, productBrief?: ProductDesignBrief): string {
    const contract = visualContract || this.getVisualContract(spec);
    const isKanbanForbidden = ((spec as any).forbiddenPatterns || []).includes("KanbanBoard");
    const isKanbanExplicitlyRequested = (
      (spec.features || []).some((f: any) => {
        const name = (typeof f === "string" ? f : (f?.name || f?.title || "")).toLowerCase();
        return (
          name.includes("kanban") ||
          name.includes("task board") ||
          name.includes("scrum board") ||
          name.includes("workflow board") ||
          name.includes("task management") ||
          name.includes("project management") ||
          (/\bboard\b/.test(name) && !name.includes("dashboard") && !name.includes("leaderboard") && !name.includes("order book"))
        );
      }) ||
      ((spec as any).userPrompt && /\b(kanban|task board|scrum board|sprint board|issue board|task management)\b/i.test((spec as any).userPrompt)) ||
      ((spec as any).description && /\b(kanban|task board|scrum board|sprint board|issue board|task management)\b/i.test((spec as any).description))
    );
    const hasKanban = !isKanbanForbidden && isKanbanExplicitlyRequested;

    // ── If a ProductDesignBrief is present, prepend the full locked mandate ─────────────────────────
    let briefMandate = "";
    if (productBrief) {
      const b = productBrief;
      const pages = b.pageCompositions;
      briefMandate = `
══════════════════════════════════════════════════════════════
ANTI-AI-WEBSITE PRINCIPLE — MANDATORY
══════════════════════════════════════════════════════════════
Every visual component, layout pattern, navigation structure,
terminology, and color treatment must be traceable to this
ProductDesignBrief, the user's requirements, the selected design
direction, or a justified reusable design-system primitive.

You are implementing a design that has already been decided.
You are not designing.
══════════════════════════════════════════════════════════════

PRODUCT DESIGN MANDATE [briefId: ${b.briefId}]
────────────────────────────────────────────────
Experience  : ${b.productCharacteristics.experiencePattern}
Audience    : ${b.productCharacteristics.audienceContext.isPersonal ? "personal" : b.productCharacteristics.audienceContext.isProfessional ? "professional" : "consumer"} | ${b.productCharacteristics.audienceContext.techSavviness} tech-savviness
Direction   : ${b.artDirectionName} — ${b.artDirectionRationale}
Primary     : ${b.featurePriority.informationArchitecture.primaryInteraction}
Tone        : ${b.productCharacteristics.emotionalTone.primary}${b.productCharacteristics.emotionalTone.secondary ? " + " + b.productCharacteristics.emotionalTone.secondary : ""}

NAVIGATION
──────────
Strategy         : ${b.navigation.strategy}
Max PRIMARY items: ${b.navigation.maxPrimaryItems} — HARD CAP. DO NOT EXCEED.
Secondary nav    : ${b.navigation.secondaryNav?.description || "none"}

PRIMARY NAVIGATION CONTRACT (MANDATORY):
Maximum: ${b.navigation.maxPrimaryItems} items.
All other routes MUST be:
- secondary navigation
- More menu
- contextual action
- page-local navigation
Do not render all routes in primary navigation. Layout and Navbar must have <= ${b.navigation.maxPrimaryItems} primary links.

COLOR SYSTEM
─────────────
Background  : ${b.colorSystem.background}
Surface     : ${b.colorSystem.surface}
Primary     : ${b.colorSystem.primary}
PrimaryHover: ${b.colorSystem.primaryHover}
Text Primary: ${b.colorSystem.textPrimary}
Text Muted  : ${b.colorSystem.textMuted}
Chart Colors: [${b.colorSystem.chartPalette.join(", ")}]
              — Use ALL 6 across charts. NOT 1 color with opacity variants.

TYPOGRAPHY
──────────
Display Font: ${b.typography.displayFont}
Body Font   : ${b.typography.bodyFont}
Scale       : ${b.typography.displayScale}
Headings    : ${b.typography.headingStyle}

GEOMETRY
────────
Radius SM: ${b.geometry.radiusSm} | MD: ${b.geometry.radiusMd} | LG: ${b.geometry.radiusLg} | XL: ${b.geometry.radiusXl}
Shadow   : ${b.geometry.shadowStyle} | Borders: ${b.geometry.borderWidth}

PAGE COMPOSITIONS (each must be distinct — see rule below)
───────────────────────────────────────────────────
COMPOSITION RULE: No more than 2 consecutive pages may share
the same compositionFamily AND heroElement type. Intentional
reuse of a composition family for genuinely similar pages is
acceptable. Mechanical repetition is not.

${pages.map(p => `│ ${p.route} — ${p.name}
│   Hero    : ${p.heroElement} — ${p.primaryFocus}
│   Support : ${p.secondaryElements.join(", ")}
│   Rhythm  : ${p.visualRhythm}
│   NEVER   : ${p.forbiddenPatterns.join(", ")}`).join("\n")}

VOCABULARY CONTRACT
───────────────────
  ✓ REQUIRED  (must appear at least once in the app): ${b.vocabularyContract.required.join(", ") || "(none defined)"}
  ○ PREFERRED (use naturally where appropriate):       ${b.vocabularyContract.preferred.join(", ")}
  ✗ FORBIDDEN (never in JSX text, labels, headings):  ${b.vocabularyContract.forbidden.join(", ")}

DESIGN PRINCIPLES
─────────────────
${b.designPrinciples.map(p => "  ✓ " + p).join("\n")}

ANTI-PATTERNS (WILL FAIL DESIGN INTENT GATE)
─────────────────────────────────────────────
${b.globalForbiddenPatterns.map(p => "  ✗ " + p).join("\n")}
══════════════════════════════════════════════════════════════
`;
    }

    return briefMandate + `
DOMAIN VISUAL DESIGN CONTRACT — MANDATORY USAGE:
Domain: ${contract.domain} (${contract.productType})
Visual Personality: ${contract.visualPersonality.mood} [Formality: ${contract.visualPersonality.formality}, Density: ${contract.visualPersonality.density}]
Layout Archetype: ${contract.layoutFamily}
Navigation Strategy: ${contract.navigation.strategy}

Color Palette Tokens:
  Background: ${contract.colorSystem.background}
  Surface / Cards: ${contract.colorSystem.card}
  Primary Accent: ${contract.colorSystem.primary} (${contract.colorSystem.accent})
  Text Primary: ${contract.colorSystem.textPrimary}
  Text Muted: ${contract.colorSystem.textMuted}
  Badges: ${contract.colorSystem.badgeStyle}
  Active Nav: ${contract.colorSystem.activeNavStyle}

Pre-generated Specialized Components available in src/design-system/:
  import { Button, GlassCard, Badge, Input, Select, PageHeader, MetricCard, Skeleton, EmptyState, Timeline${hasKanban ? ', KanbanBoard' : ''}, TelemetryGrid, ShowcaseGrid } from '../design-system';

ANTI-PATTERNS (STRICTLY PROHIBITED):
${contract.antiPatterns.map(a => `  ✗ ${a}`).join('\n')}

REQUIRED COMPONENT PATTERNS:
  ✓ Use domain-appropriate components: ${contract.components.join(', ')}
  ✓ Follow layout family ${contract.layoutFamily} (NOT a generic card-grid CRUD template)
  ✓ Navigation must match ${contract.navigation.strategy}
  ✓ Every interactive element has hover + focus-visible states matching ${contract.colorSystem.primary}
  ✓ Empty states use EmptyState with domain call-to-action
`;
  }
}
