export const PROMPT_VERSIONS = {
  AEGIS_SYSTEM: "AEGIS_SYSTEM_V1",
  SPECIFICATION: "SPECIFICATION_V1",
  ARCHITECTURE: "ARCHITECTURE_V1",
  TASK_PLANNER: "TASK_PLANNER_V1",
  CODER: "CODER_V1",
  DATA_ARCHITECTURE: "DATA_ARCHITECTURE_V1",
  HEALER: "HEALER_V1",
  REVIEWER: "REVIEWER_V1",
  VISUAL_REVIEWER: "VISUAL_REVIEWER_V1",
  REALITY_CHECKER: "REALITY_CHECKER_V1",
  FINAL_AUDITOR: "FINAL_AUDITOR_V1",
  FEATURE_ADDITION: "FEATURE_ADDITION_V1",
} as const;

export type PromptVersionKey = keyof typeof PROMPT_VERSIONS;
