packages: []
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
confirmModulesPurge: false
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
