export enum ExecutionPhase {
  Requirements = "Requirements",
  Architecture = "Architecture",
  Planning = "Planning",
  DataModeling = "DataModeling",
  ApiDesign = "ApiDesign",
  Database = "Database",
  Backend = "Backend",
  Frontend = "Frontend",
  Implementation = "Implementation",
  Review = "Review",
  Validation = "Validation",
  Build = "Build",
  Repair = "Repair",
  Complete = "Complete",
}
